### ISSUE TITLE
READMEが古い

### ISSUE THREAD

**Issue by amenoci** [otoduki/san_tango_san#3]
https://github.com/otoduki/san_tango_san/commit/5dfe218f76b2a4b3563b983f17e171ddf13efb69#diff-04c6e90faac2675aa89e2176d2eec7d8R1

前のリポジトリの名前になっているので更新する

**Comment by amenoci** [comment]
@takoh-1710 お願いしま

**Comment by takoh-1710** [comment]
修正しました

**Comment by amenoci** [comment]
masterブランチに直接コミットが積まれているようなので以下の対応をお願いします
- masterブランチの本件に関するコミットをrevert
- developブランチからfeatureブランチを切って本件の対応のコミットを積む
- developブランチへのプルリクを作る

reopenしま

**Comment by amenoci** [comment]
#9 で対応完了

クローズ
